steps:
  - checkout: none # skip checking out the default repository resource
  - task: PowerShell@2
    name: Vars
    displayName: "Pick Primary/Secondary deployment target"
    inputs:
      targetType: "inline"
      script: |
        if ("$(enableDisasterRecoveryDeploy)" -eq "false") {
          Write-Host "##vso[task.setvariable variable=AppServiceName;isOutput=true]$(PrimaryAppServiceName)"
          Write-Host "##vso[task.setvariable variable=AppResourceGroup;isOutput=true]$(PrimaryResourceGroup)"
        } else {
          Write-Host "##vso[task.setvariable variable=AppServiceName;isOutput=true]$(SecondaryAppServiceName)"
          Write-Host "##vso[task.setvariable variable=AppResourceGroup;isOutput=true]$(SecondaryResourceGroup)"
        }
