trigger: none # this pipeline only runs when triggered by a successful build, not on push

resources:
  pipelines:
    - pipeline: buildPipeline # alias used below to reference this resource
      source: "WebAppBuildPipelineName" # name of the build pipeline in Azure DevOps
      trigger:
        branches:
          include:
            - main
            - hotfix/*
            - release/*
            - feature/*

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: templates/deploy-template.yml
    parameters:
      environment: QA
      environmentName: Sample-WebApp-QA
      enableDisasterRecoveryDeploy: $(enableDisasterRecoveryDeploy)

  - template: templates/deploy-template.yml
    parameters:
      environment: Prod
      environmentName: Sample-WebApp-Prod
      dependsOnStage: DeployQA
      enableDisasterRecoveryDeploy: $(enableDisasterRecoveryDeploy)
      # only deploy to Prod if the triggering build was run against main or release/*
      branchCondition: "or(eq(resources.pipeline.buildPipeline.sourceBranch, 'refs/heads/main'), startsWith(resources.pipeline.buildPipeline.sourceBranch, 'refs/heads/release/'), startsWith(resources.pipeline.buildPipeline.sourceBranch, 'refs/heads/hotfix/'))" # This part is dependant on the branching strategy of the application code repo.
